namespace: pet-battle-nsfw

image:
  notebook:
    image: quay.io/ml-aml-workshop/keras-tensorflow-panda-notebook:0.0.1
  minio:
    image: docker.io/minio/minio:latest
  kogito:
    image: quay.io/eformat/pet-battle-nsfw-kogito:latest
  nsfwapi:
    image: quay.io/eformat/pet-battle-nsfw-api:latest


subscription:
  opendatahub:
    csv: opendatahub-operator.v0.6.0

odh:
  kdef:
    version: v0.7-branch-openshift

minio:
  persistence:
    accessModes: ReadWriteOnce
    volumeSize: 5Gi

#
replicaCount: 1
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
