{{- if false -}}
---
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  finalizers:
    - kfdef-finalizer.kfdef.apps.kubeflow.org
  name: opendatahub
  namespace: {{ .Values.namespace }}
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-common
      name: odh-common
    - kustomizeConfig:
        parameters:
          - name: s3_endpoint_url
            value: s3.odh.com
        repoRef:
          name: manifests
          path: jupyterhub/jupyterhub
      name: jupyterhub
    - kustomizeConfig:
        overlays:
          - additional
        repoRef:
          name: manifests
          path: jupyterhub/notebook-images
      name: notebook-images
  repos:
    - name: manifests
      uri: 'https://github.com/opendatahub-io/odh-manifests/tarball/master'
  version: {{ .Values.odh.kdef.version }}
{{- end -}}