apiVersion: v2
name: ml-aml-workshop
description: A Helm chart for installing AI-ML-Workshop
type: application
version: 0.0.1
appVersion: 0.0.1
home: https://rht-labs.github.io/helm-charts/
maintainers:
  - name: eformat
  - name: rbrigoli
  - name: fmasood
