---
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "kafka.fullname" . }}
  labels:
    {{- include "ml-aml-workshop.labels" . | nindent 4 }}
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      log.message.format.version: '2.4'
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 1
    listeners:
      plain: {}
      tls: {}
    replicas: 3
    storage:
      type: ephemeral
    version: 2.4.0
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
