---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  namespace: {{ .Values.namespace }}
  labels:
    strimzi.io/cluster: {{ include "kafka.fullname" . }}
    {{- include "ml-aml-workshop.labels" . | nindent 4 }}
  name: mlworkshop.creditcard.clean
spec:
  config:
    message.format.version: 2.4-IV1
    retention.ms: '604800000'
    segment.bytes: '1073741824'
  partitions: 10
  replicas: 1
  topicName: mlworkshop.creditcard.clean
