---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "notebook.fullname" . }}
  labels:
    {{- include "ml-aml-workshop.labels" . | nindent 4 }}
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: {{ .Values.image.notebook.image }}
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Local
