{{- if false -}}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  namespace: {{ .Values.namespace }}
  annotations:
    olm.providedAPIs: Kafka.v1beta1.kafka.strimzi.io,KafkaBridge.v1alpha1.kafka.strimzi.io,KafkaConnect.v1beta1.kafka.strimzi.io,KafkaConnectS2I.v1beta1.kafka.strimzi.io,KafkaConnector.v1alpha1.kafka.strimzi.io,KafkaMirrorMaker.v1beta1.kafka.strimzi.io,KafkaMirrorMaker2.v1alpha1.kafka.strimzi.io,KafkaTopic.v1beta1.kafka.strimzi.io,KafkaUser.v1beta1.kafka.strimzi.io,OpenDataHub.v1alpha1.opendatahub.io
  generateName: ml-aml-workshop-
  name: {{ include "odhog.fullname" . }}
  labels:
    {{- include "ml-aml-workshop.labels" . | nindent 4 }}
spec:
  targetNamespaces:
  - {{ .Values.namespace | quote }}
{{- end -}}