---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "postgresdb.fullname" . }}
  labels:
    {{- include "postgresdb.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "postgresdb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "postgresdb.labels" . | nindent 8 }}
    spec:
      containers:
        - name: postgresql
          image: {{ .Values.image.postgresdb.image }}
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRESQL_ADMIN_PASSWORD
              value: postgres
            - name: POSTGRESQL_USER
              value: ml-user
            - name: POSTGRESQL_PASSWORD
              value: ml-user
            - name: POSTGRESQL_DATABASE
              value: ml-workshop
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
---
kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "postgresdb.fullname" . }}
  labels:
    {{- include "postgresdb.labels" . | nindent 4 }}
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    {{- include "postgresdb.selectorLabels" . | nindent 6 }}
  type: ClusterIP
  sessionAffinity: None
