---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  namespace: {{ .Values.namespace }}
  name: strimzi-kafka-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: strimzi-kafka-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: {{ .Values.subscription.strimzi.csv | default "strimzi-cluster-operator.v0.17.0" | quote }}